logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
---
server:
  port: 8080
  servlet:
    context-path: /bankServices
---
keycloak:
  enabled: true
  bearer-only: true
  auth-server-url: http://localhost:8080/auth
  resource: BANK-WS
  realm: BANK
  public-client: true
  principal-attribute: preferred_username
  # credentials:
  # secret: LwmDMmjJDesuahnvhufqPxaDjOp3n7vU
  use-resource-role-mappings: false
  allowAnyHostname: true
  ssl-required: external
---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      connectionTestQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.MariaDB103Dialect


