logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
---
server:
  port: 8081
  servlet:
    context-path: /bankServices
---
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    filter: true
    validatorUrl: none
